### ISSUE TITLE
Add support for RBGWW or RBGW stripes?

### ISSUE THREAD

**Issue by JoJ123** [instalator/ioBroker.mclighting#4]
Can you please add support for RBGWW or RBGW stripes?

**Comment by instalator** [comment]
Ask the developer https://github.com/toblum/McLighting

**Comment by JoJ123** [comment]
Hey there is already a fork, that supports SK6812 LEDs with RBGW
https://github.com/FabLab-Luenen/McLighting

I will try this afternoon, if it's possible to use with your adapter.

Instead of sending just RBG the fork accept RBGW. This means, that after the RBG we just have to add the value vor W.

Example: 09ffffff+19ff0000 OR 09ffffff,19ff0000
This would then be: 09ffffff**ff**+19ff0000**00** OR 09ffffff**ff**,19ff0000**00**
